<a href="https://colab.research.google.com/github/vrshushma/dav_ls/blob/main/basic_operations_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print("1D array")
print("shape",a.shape)
print("size",a.size)
print("dimension",a.ndim)
print("length",len(a))

1D array
shape (5,)
size 5
dimension 1
length 5


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print("2D array")
print("shape",b.shape)
print("size",b.size)
print("dimension",b.ndim)
print("length",len(b))

2D array
shape (2, 3)
size 6
dimension 2
length 2


In [ ]:
c = np.array([[[1,2],[2,3],[3,7]]])
print("3D array")
print("shape",c.shape)
print("size",c.size)
print("dimension",c.ndim)
print("length",len(c))

3D array
shape (1, 3, 2)
size 6
dimension 3
length 1


In [ ]:
odd_numbers = np.arange(-29,11,2)
print(odd_numbers)

[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]


In [ ]:
num_students = 50
student_marks = np.random.randint(0,100,num_students)
passed_students_count = np.sum(student_marks >= 30)
failed_students_count = np.sum(student_marks < 30)
print("Passed students count",passed_students_count)
print("Failed students count",failed_students_count)

Passed students count 40
Failed students count 10


In [ ]:
import numpy as np

# Create an array of 5 evenly spaced numbers between 0 and 10
space = np.linspace(0, 10, 5)
print(space)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np

# Create a 1D array of 5 ones (all elements set to 1)
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
import numpy as np

# Create a 1D array of 5 zeros (all elements set to 0)
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

# Create a 1D array
data = np.array([1, 2, 3, 4])

# Create a diagonal matrix with the elements from the 1D array
diagonal_matrix = np.diag(data)
print(diagonal_matrix)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
numbers = [1, 2, 3, 4, 5]
total_sum = sum(numbers)
print("The sum of the numbers is:", total_sum)


The sum of the numbers is: 15


In [ ]:
a = [4, 8, 1, 9, 3, 5]
min_value = min(a)
print(min_value)

1


In [ ]:
numbers = [3, 7, 1, 9, 4]
largest_number = max(numbers)
print(largest_number)

9


In [ ]:
import statistics
data = [2, 5, 1, 8, 3]
avg = statistics.mean(data)
print(avg)

3.8


In [ ]:
import numpy as np
rows = 5
cols = 3
random_array = np.random.randint(1,51, size=(rows, cols))
print(random_array)


[[37  6 13]
 [11 20 49]
 [45 23 33]
 [23  3 25]
 [44 28 45]]


In [ ]:
odd_numbers = np.arange(-30,10)
print(odd_numbers)

[-30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13
 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5
   6   7   8   9]


In [ ]:
shape = (2, 3, 4)
random_numbers = np.random.randint(10,41, size=shape)
print(random_numbers)

[[[39 25 32 22]
  [25 28 34 31]
  [38 13 21 13]]

 [[26 28 33 39]
  [31 32 26 35]
  [29 12 32 39]]]


In [ ]:
import numpy as np
shape = (3, 2, 3)
ones_array = np.ones(shape, dtype=int)
print(ones_array)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
